In [142]:
import numpy as np
np.__version__

'1.13.1'

In [143]:
np?

In [144]:
L = list(range(10))

In [145]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [146]:
type(L[0])

int

In [147]:
type(L[0])

int

In [148]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [149]:
type(L2[0])

str

In [150]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [151]:
import array

In [152]:
L = list(range(10))

In [153]:
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.array([1, 4,2,5,3]) #create arrays from Python lists

array([1, 4, 2, 5, 3])

In [155]:
np.array([1, 4,2,5,3]) #create arrays from Python lists

array([1, 4, 2, 5, 3])

In [156]:
np.array([3.14, 4, 2, 3]) #If types do not match, NumPy will upcast if possible (here, integers are
                            #upcast to floating point)

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [157]:
np.array([1, 2, 3, 4], dtype='float32') #dtype explicitly set the data type

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [158]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# #Creating arrays from scratch

In [159]:
#Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [160]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [161]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [162]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [163]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [164]:
# Crreate a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[ 0.65279032,  0.63505887,  0.99529957],
       [ 0.58185033,  0.41436859,  0.4746975 ],
       [ 0.6235101 ,  0.33800761,  0.67475232]])

In [165]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [166]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [167]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [168]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([ 1.,  1.,  1.])

# NumPy Array Attributes

In [169]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [170]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [171]:
print("x3 data type is ",x3.dtype )

x3 data type is  int32


In [172]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


# Array Indexing: Accessing Single Elements

In [173]:
x1

array([5, 0, 3, 3, 7, 9])

In [174]:
x1[0],x1[3]

(5, 3)

In [175]:
x1[4]

7

In [176]:
x1[-1] #negative indices index from the end of an array

9

In [177]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [178]:
x2[0,0]

3

In [179]:
x2[1,0]

7

In [180]:
x2[2,2]

7

In [181]:
x2[0,0]==x2[1,0]

False

In [182]:
x2[1,0]==x2[2,2]

True

In [183]:
x2[0,0]==x2[0,0]

True

In [184]:
x2[0,0]=25

In [185]:
x2

array([[25,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [186]:
x1[0] = 3.14159 #you attempt to insert a floating-point value to an integer array, the value will be silently truncated.

In [187]:
x1 #the value of x1[0] in cell below is 3 not 3.14159

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

In [188]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [190]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [191]:
x[4:7]

array([4, 5, 6])

In [192]:
x[4:7:2]

array([4, 6])

In [193]:
x[::2]

array([0, 2, 4, 6, 8])

In [194]:
x[1::2]

array([1, 3, 5, 7, 9])

In [195]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [196]:
x[5::-2]

array([5, 3, 1])

In [197]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [198]:
x2

array([[25,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [199]:
x2[:2, :3] # two rows, three columns

array([[25,  5,  2],
       [ 7,  6,  8]])

In [200]:
x2[:3,::2] # all rows, every other column

array([[25,  2],
       [ 7,  8],
       [ 1,  7]])

In [201]:
x2[::,::2]

array([[25,  2],
       [ 7,  8],
       [ 1,  7]])

In [202]:
x2[::,::]

array([[25,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [203]:
x2[:,0]

array([25,  7,  1])

In [204]:
x2

array([[25,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [205]:
print(x2[:,0]) # first column of x2

[25  7  1]


In [206]:
print(x2[0,:])# first row of x2

[25  5  2  4]


In [207]:
print(x2[0]) # equivalent to x2[0, :]

[25  5  2  4]


In [208]:
print(x2)

[[25  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [209]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[25  5]
 [ 7  6]]


In [210]:
x2_sub[0, 0] = 99 #if we modify this subarray, we’ll see that the original array is changed!
print(x2_sub)

[[99  5]
 [ 7  6]]


In [211]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [212]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [213]:
#now modify this subarray, the original array is not touched
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [214]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [216]:
np.random.random((3,3))

array([[ 0.65279032,  0.63505887,  0.99529957],
       [ 0.58185033,  0.41436859,  0.4746975 ],
       [ 0.6235101 ,  0.33800761,  0.67475232]])

In [217]:
a = np.arange(0,10)
s = a[2:9:2]
s

array([2, 4, 6, 8])

In [220]:
b = np.arange(0,20)
s1=slice(2,19,2)
b[s1]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [221]:
b[5]

5

In [222]:
b[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [223]:
b[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])