# Lab notebook - week 2

### * A note about cell output - expressions vs. statements

In [170]:
# Some code fragments produce output, see the red "Out[?]" below - such fragments are called expressions.
5 + 2

7

In [171]:
# Other fragments produce no output. Such fragments are called statements. Not that there is no "Out[]" below this cell.
x = 5 + 2

In [172]:
# If you want to see the value of x, just write x on another line, "x" is an "expression" and produces the value of x as output
y = 3 + 7
y

10

In [173]:
# A cell only produces one output - that of the last expression in the cell
x  # value of x is not shown
y 

10

In [174]:
# If you want to see several values, output them from different cells or use print()
# note that print() produces text, but it is not labeled as Out[] (why?)
print(x)
print(y)

7
10


## NumPy basics
Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [175]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [176]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [177]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [178]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [179]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([ 0.,  0.,  0.,  0.,  0.])

In [180]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [181]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([ 0.98407799,  0.63150171,  0.66721309,  0.62389224,  0.20113469,
        0.32816304])

In [182]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([69, 35, 26, 67, 93, 58])

### Array properties

In [183]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [184]:
# The total number of elements
b.size 

6

In [185]:
# number of dimensions
b.ndim 

2

In [186]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [187]:
# Data type of the array
a.dtype

dtype('int32')

In [188]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [189]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)  
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


#### Convert a list into a numpy array

In [190]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [191]:
# your code here
x = np.array([5, 3, 8, 4])
x

array([5, 3, 8, 4])

#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [192]:
# Feel free to add more cells


#### Create an array of 10 ones

In [193]:
arr = np.ones(10)
arr

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [194]:
#### Create an array of 10 fives
arr5s = np.full(10, 5)

In [195]:
arr5s

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [196]:
#### Create an array of the integers from 10 to 50 (including 50)

In [197]:
arr10_50 = np.arange(10, 51)
arr10_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [198]:
#### Create an array of 10 random numbers between 0 and 5 (not integers)

In [199]:
np.random.uniform(low=0.0, high=5.0, size=10)

array([ 3.18542378,  2.32092458,  3.80577778,  0.97222674,  0.78918554,
        1.51709774,  3.17316718,  4.47015404,  0.41913272,  4.77298744])

In [200]:
#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2

In [201]:
np.linspace(0, 2, num=11, endpoint=True, retstep=False, dtype=None)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [202]:
#### Create a 3 by 4 array of ones

In [203]:
arr_ones = np.ones((3, 4))
arr_ones

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [204]:
#### Create a 3 by 4 array of fives

In [205]:
np.full_like(arr_ones, 5)

array([[ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.]])

In [206]:
#### Create a 3x3 matrix with values ranging from 0 to 8 (use reshape)

In [207]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Element selection
Using the following arrays `a` and `m`

In [208]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [209]:
m = np.arange(1,22).reshape((3,7))
m

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Create an array containing... 
#### the first 4 elements of a

In [210]:
a[:4]

array([10, 11, 12, 13])

#### the last 3 elements of a

In [211]:
a[8:]

array([18, 19, 20])

#### The middle elements of a from 15 to 18 inclusive

In [212]:
a[5:9]

array([15, 16, 17, 18])

#### The first column of m

In [213]:
m[:,0]

array([ 1,  8, 15])

#### The middle row of m

In [214]:
m[1:2,::]

array([[ 8,  9, 10, 11, 12, 13, 14]])

#### The left 3 columns of m

In [215]:
v = m[::,0:3]
v

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17]])

#### The bottom-right 2 by 2 square

In [216]:
v[1:3,1:3]

array([[ 9, 10],
       [16, 17]])

#### (bonus) every other element of a  

In [217]:
a[1::2]

array([11, 13, 15, 17, 19])

#### Subtract 5 from each element of a

In [218]:
a-5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

In [219]:
arr_sq = np.arange(1,11)**2
arr_sq

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

In [220]:
arr_two_power = 2**np.arange(0,11)
arr_two_power

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024], dtype=int32)

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

In [223]:
arr_two_power - 1

array([   0,    1,    3,    7,   15,   31,   63,  127,  255,  511, 1023], dtype=int32)

### Bonus task
Write code that lists all available dtypes with specified number of bits 

In [222]:
# Hint
np.int8

numpy.int8