In [1]:
import numpy as np

In [2]:
list1 = [0,1,2,3,4]

In [3]:
list1

[0, 1, 2, 3, 4]

In [4]:
arrId = np.array(list1)

In [5]:
arrId

array([0, 1, 2, 3, 4])

In [6]:
arrId + 3

array([3, 4, 5, 6, 7])

In [14]:
list1[::2]

[0, 2, 4]

In [15]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]

In [16]:
list2

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [19]:
arrId2 = np.array(list2)
arrId2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

In [30]:
arrId2[1:2,:3]

array([[3, 4, 5]])

In [32]:
arrId2.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [38]:
arrId3 = arrId2[::-1,::-1]
arrId3 

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [37]:
arrId2.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [39]:
arrId3.transpose()

array([[8, 5, 2],
       [7, 4, 1],
       [6, 3, 0]])

In [48]:
np.arange(40)[1:40:3]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [49]:
X,Y = np.mgrid[-5:5.1:0.5, -5:5.1:0.5]

In [50]:
X, Y

(array([[-5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. ,
         -5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. , -5. ],
        [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5,
         -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
        [-4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. ,
         -4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. , -4. ],
        [-3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5,
         -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5, -3.5],
        [-3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. ,
         -3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. , -3. ],
        [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5,
         -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
        [-2. , -2. , -2. , -2. , -2. , -2. , -2. , -2. , -2. , -2. , -2. ,
         -2. , -2. , -2. , -2. , -2. , -2. , -2. , -2. 